### ISSUE TITLE
TypeError with input made by STARFISH

### ISSUE THREAD

**Issue by sethb3744** [JEFworks/MERmaid#8]
Hi, I used STARFISH, a program that analyzes transcriptome imaging, to produce a data.csv.gz file for visualization with MERmaid. However, there are 3 TypeErrors associated with the same object, called **this.props.color**, which seems to be Null/undefined. I believe this may be an issue with STARFISH, as the way they write the file might be out of date. A link to the data.csv.gz file is below. Can you please give me some insight on whether the file is out of date or if it is an issue with MERmaid? Thank you.
https://drive.google.com/file/d/1Uzq9U5iKa466E8FPrJEwq_2wV3AnaMCu/view?usp=sharing

To be clear, I rebuilt using "npm install" and then opened this tab using "npm start". When I tried running without re-building, I simply got the error message "code 404, message File not found", which seems to be a separate issue.

![screen shot 2019-02-13 at 4 36 04 pm](https://user-images.githubusercontent.com/10657968/52753948-893f8580-2fad-11e9-960d-2f4ec7ba9884.png)
![screen shot 2019-02-13 at 4 36 20 pm](https://user-images.githubusercontent.com/10657968/52753954-8b094900-2fad-11e9-806e-630368ada64e.png)

**Comment by JEFworks** [comment]
Please ensure you are on the starfish branch: https://github.com/JEFworks/MERmaid/tree/starfish 
The master branch has addition features such as visualizing segmentation boundaries and immunofluorescence stains that have not been updated in STARFISH.

**Comment by sethb3744** [comment]
Thank you for your quick response! I tried using that branch of MERmaid, but the same issue is still there. 

When I run with "python -m http.server 8080," the warning saying "code 404, message File not found" is now gone thankfully, but the window on my browser is simply black and doesn't load anything.

When I run with "npm start," the same TypeError that I showed before is there. On the Terminal, I see the following warnings:
./src/index.js
  Line 123:  Missing radix parameter                       radix
  Line 124:  Missing radix parameter                       radix
  Line 125:  Missing radix parameter                       radix
  Line 134:  Expected to return a value in arrow function  array-callback-return
  Line 136:  Expected to return a value in arrow function  array-callback-return
  Line 162:  'options' is assigned a value but never used  no-unused-vars

**Comment by JEFworks** [comment]
The column headers in your data.csv.gz file currently must be 
```
x,y,gene1,gene2
```

Previously versions automatically detected the column header names, but that make it difficult to distinguish between different feature types (features that needed factor-based colors, versus features that needed continuous colors, versus features that represented cell boundaries, etc). Ideally there would be a config file to deal with this. Feel free to open a feature request if you think that would be useful.

**Comment by sethb3744** [comment]
That fixed it for me. Thank you!
