### ISSUE TITLE
Download and citation for all data?

### ISSUE THREAD

**Issue by mccalluc** [JEFworks/MERmaid#9]
Hi: Do you think it would be ok to use the data you have here as another demo in [Vitessce](http://vitessce.io), which I'm working on for Peter? I see the link for the molecules csv, but is there a good way to get the background bitmap or the cell outlines?

**Comment by JEFworks** [comment]
Hi Chuck. Sure, feel free. The background bitmap is: https://github.com/JEFworks/MERmaid/blob/master/docs/bg.png
The citation for the data is: Guiping Wang et al. (Nature Scientific Reports, 2018)
